name: Publish Docker Image CI
on:
    push:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: ilteoood/docker_buildx@master
        name: Build & push Docker image
        with:
          publish: true
          dockerFile: Dockerfile
          imageName: miclon/chatgpt
          tag: latest
          platform: linux/amd64
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
